name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare artifact
        run: |
          mkdir site
          cp index.html code.js site/

      - uses: actions/upload-pages-artifact@v1
        with:
          path: site

      - uses: actions/deploy-pages@v1
